# FILL IN THE MISSING VALUES BELOW
alerting:
  github:
    repository-url: "https://github.com/louxer-crakers/devops-jatim-25"
    token: "<github-token>" # WARN: DO NOT CHANGE THIS LINE
# FILL IN THE MISSING VALUES ABOVE

# FILL IN THE MISSING VALUES BELOW
endpoints:
  - name: Leantime
    url: <leantime-url> # WARN: DO NOT CHANGE THIS LINE
    interval: 30s
    conditions: 
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
    alerts:
      - type: github
        failure-threshold: 3
        success-threshold: 5
        send-on-resolved: true
        description: "Sensei, Leantime is down! Please check and fix it."

  - name: Gatus
    url: <gatus-url> # WARN: DO NOT CHANGE THIS LINE
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"
    alerts:
      - type: github
        failure-threshold: 3
        success-threshold: 5
        send-on-resolved: true
        description: "Sensei, Gatus is down! Please check and fix it."

  - name: Nginx thesaes
    url: http://35.168.110.160 # WARN: DO NOT CHANGE THIS LINE
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"
    alerts:
      - type: github
        failure-threshold: 3
        success-threshold: 5
        send-on-resolved: true
        description: "Sensei, Thesa is down! Please check and fix it."
# FILL IN THE MISSING VALUES BELOW
